//! GENERATED by `pulse gen` from IR fnv1a64:1280b212dc18e23e. Do not edit.

/// The IR this firmware was generated from; its evidence (`pulse check`) is bound to the same hash.
pub const IR_HASH: &core::ffi::CStr = c"fnv1a64:1280b212dc18e23e";

pub struct Firmware {
    pub __tick_40: f32,
    pub position_loop__last_target: f32,
    pub position_loop__pid__integral: f32,
    pub position_loop__pid__prev_meas: f32,
    pub position_loop__pid__has_prev: bool,
    pub position_loop__pid__filt: f32,
    pub position_loop__pid__filt_init: bool,
    pub position_loop__pid__bad: f32,
    pub position_loop__amps__held: f32,
    pub thermal_fsm__mode: f32,
    pub thermal_fsm__state__held: f32,
    pub thermal_fsm__scale__held: f32,
    pub current_loop__pid__integral: f32,
    pub current_loop__pid__prev_meas: f32,
    pub current_loop__pid__has_prev: bool,
    pub current_loop__pid__filt: f32,
    pub current_loop__pid__filt_init: bool,
    pub current_loop__pid__bad: f32,
}

impl Default for Firmware {
    fn default() -> Self {
        Self::new()
    }
}

impl Firmware {
    pub const fn new() -> Self {
        Self {
            __tick_40: 0.0_f32,
            position_loop__last_target: 0.0_f32,
            position_loop__pid__integral: 0.0_f32,
            position_loop__pid__prev_meas: 0.0_f32,
            position_loop__pid__has_prev: false,
            position_loop__pid__filt: 0.0_f32,
            position_loop__pid__filt_init: false,
            position_loop__pid__bad: 0.0_f32,
            position_loop__amps__held: 0.0_f32,
            thermal_fsm__mode: 0.0_f32,
            thermal_fsm__state__held: 0.0_f32,
            thermal_fsm__scale__held: 0.0_f32,
            current_loop__pid__integral: 0.0_f32,
            current_loop__pid__prev_meas: 0.0_f32,
            current_loop__pid__has_prev: false,
            current_loop__pid__filt: 0.0_f32,
            current_loop__pid__filt_init: false,
            current_loop__pid__bad: 0.0_f32,
        }
    }

    pub fn step(&mut self, v_sensor__theta: f32, v_sensor__current: f32, v_sensor__temp: f32, v_command__theta: f32) -> (f32, f32, f32,) {
        let v___fire_40 = (self.__tick_40 == 0.0_f32);
        let v___bump_40 = (self.__tick_40 + 1.0_f32);
        let v_position_loop__tgt = (if v_command__theta.is_finite() { v_command__theta.max((-10.0_f32)).min(10.0_f32) } else { self.position_loop__last_target });
        let v_position_loop__pid__ok = v_sensor__theta.is_finite();
        let v_position_loop__pid__lost = ((!v_position_loop__pid__ok) && (self.position_loop__pid__bad >= 3.0_f32));
        let v_position_loop__pid__rst = (false || v_position_loop__pid__lost);
        let v_position_loop__pid__meas = (if v_sensor__theta.is_finite() { v_sensor__theta } else { self.position_loop__pid__prev_meas });
        let v_position_loop__pid__error = (v_position_loop__tgt - v_position_loop__pid__meas);
        let v_position_loop__pid__p_term = (1.8_f32 * v_position_loop__pid__error);
        let v_position_loop__pid__raw_d = (if self.position_loop__pid__has_prev { ((self.position_loop__pid__prev_meas - v_position_loop__pid__meas) / 0.005_f32) } else { 0.0_f32 });
        let v_position_loop__pid__filt_d = (if self.position_loop__pid__filt_init { ((1.0_f32 * v_position_loop__pid__raw_d) + ((1.0_f32 - 1.0_f32) * self.position_loop__pid__filt)) } else { v_position_loop__pid__raw_d });
        let v_position_loop__pid__d_term = (0.108_f32 * v_position_loop__pid__filt_d);
        let v_position_loop__pid__cand = (self.position_loop__pid__integral + ((6.0_f32 * v_position_loop__pid__error) * 0.005_f32));
        let v_position_loop__pid__unsat = ((v_position_loop__pid__p_term + v_position_loop__pid__cand) + v_position_loop__pid__d_term);
        let v_position_loop__pid__out = (if v_position_loop__pid__lost { 0.0_f32 } else { v_position_loop__pid__unsat.max((-8.0_f32)).min(8.0_f32) });
        let v_position_loop__pid__deeper = (((v_position_loop__pid__unsat > 8.0_f32) && (v_position_loop__pid__error > 0.0_f32)) || ((v_position_loop__pid__unsat < (-8.0_f32)) && (v_position_loop__pid__error < 0.0_f32)));
        let v_position_loop__amps = v_position_loop__pid__out;
        let v_position_loop__amps__now = (if v___fire_40 { v_position_loop__amps } else { self.position_loop__amps__held });
        let v_thermal_fsm__state = (if ((v_sensor__temp > 100.0_f32) || (!v_sensor__temp.is_finite())) { 2.0_f32 } else { (if ((self.thermal_fsm__mode == 0.0_f32) && (v_sensor__temp > 80.0_f32)) { 1.0_f32 } else { (if ((self.thermal_fsm__mode == 1.0_f32) && (v_sensor__temp < 70.0_f32)) { 0.0_f32 } else { self.thermal_fsm__mode }) }) });
        let v_thermal_fsm__scale = (if (v_thermal_fsm__state == 0.0_f32) { 1.0_f32 } else { (if (v_thermal_fsm__state == 1.0_f32) { 0.75_f32 } else { 0.0_f32 }) });
        let v_thermal_fsm__state__now = (if v___fire_40 { v_thermal_fsm__state } else { self.thermal_fsm__state__held });
        let v_thermal_fsm__scale__now = (if v___fire_40 { v_thermal_fsm__scale } else { self.thermal_fsm__scale__held });
        let v_current_loop__lim = (if (v_thermal_fsm__scale__now >= 0.0_f32) { (8.0_f32 * v_thermal_fsm__scale__now.min(1.0_f32)) } else { 0.0_f32 });
        let v_current_loop__setpoint = (if v_position_loop__amps__now.is_finite() { v_position_loop__amps__now.max((-v_current_loop__lim)).min(v_current_loop__lim) } else { 0.0_f32 });
        let v_current_loop__fault = (v_thermal_fsm__state__now == 2.0_f32);
        let v_current_loop__pid__ok = v_sensor__current.is_finite();
        let v_current_loop__pid__lost = ((!v_current_loop__pid__ok) && (self.current_loop__pid__bad >= 3.0_f32));
        let v_current_loop__pid__rst = (v_current_loop__fault || v_current_loop__pid__lost);
        let v_current_loop__pid__meas = (if v_sensor__current.is_finite() { v_sensor__current } else { self.current_loop__pid__prev_meas });
        let v_current_loop__pid__error = (v_current_loop__setpoint - v_current_loop__pid__meas);
        let v_current_loop__pid__p_term = (1.26_f32 * v_current_loop__pid__error);
        let v_current_loop__pid__raw_d = (if self.current_loop__pid__has_prev { ((self.current_loop__pid__prev_meas - v_current_loop__pid__meas) / 0.000125_f32) } else { 0.0_f32 });
        let v_current_loop__pid__filt_d = (if self.current_loop__pid__filt_init { ((1.0_f32 * v_current_loop__pid__raw_d) + ((1.0_f32 - 1.0_f32) * self.current_loop__pid__filt)) } else { v_current_loop__pid__raw_d });
        let v_current_loop__pid__d_term = (0.0_f32 * v_current_loop__pid__filt_d);
        let v_current_loop__pid__cand = (self.current_loop__pid__integral + ((1257.0_f32 * v_current_loop__pid__error) * 0.000125_f32));
        let v_current_loop__pid__unsat = ((v_current_loop__pid__p_term + v_current_loop__pid__cand) + v_current_loop__pid__d_term);
        let v_current_loop__pid__out = (if v_current_loop__pid__lost { 0.0_f32 } else { v_current_loop__pid__unsat.max((-24.0_f32)).min(24.0_f32) });
        let v_current_loop__pid__deeper = (((v_current_loop__pid__unsat > 24.0_f32) && (v_current_loop__pid__error > 0.0_f32)) || ((v_current_loop__pid__unsat < (-24.0_f32)) && (v_current_loop__pid__error < 0.0_f32)));
        let v_current_loop__volts = (if v_current_loop__fault { 0.0_f32 } else { v_current_loop__pid__out });
        let v_current_loop__volts__now = v_current_loop__volts;
        let v_current_loop__setpoint__now = v_current_loop__setpoint;
        let v_actuator__volts = v_current_loop__volts__now;
        let v_telemetry__thermal_state = v_thermal_fsm__state__now;
        let v_telemetry__setpoint = v_current_loop__setpoint__now;
        let n___tick_40 = (if (v___bump_40 >= 40.0_f32) { 0.0_f32 } else { v___bump_40 });
        let n_position_loop__last_target = (if v___fire_40 { v_position_loop__tgt } else { self.position_loop__last_target });
        let n_position_loop__pid__integral = (if v___fire_40 { (if v_position_loop__pid__rst { 0.0_f32 } else { (if v_position_loop__pid__deeper { self.position_loop__pid__integral } else { v_position_loop__pid__cand }).max((-8.0_f32)).min(8.0_f32) }) } else { self.position_loop__pid__integral });
        let n_position_loop__pid__prev_meas = (if v___fire_40 { (if v_position_loop__pid__rst { 0.0_f32 } else { v_position_loop__pid__meas }) } else { self.position_loop__pid__prev_meas });
        let n_position_loop__pid__has_prev = (if v___fire_40 { (!v_position_loop__pid__rst) } else { self.position_loop__pid__has_prev });
        let n_position_loop__pid__filt = (if v___fire_40 { (if v_position_loop__pid__rst { 0.0_f32 } else { v_position_loop__pid__filt_d }) } else { self.position_loop__pid__filt });
        let n_position_loop__pid__filt_init = (if v___fire_40 { (!v_position_loop__pid__rst) } else { self.position_loop__pid__filt_init });
        let n_position_loop__pid__bad = (if v___fire_40 { (if v_position_loop__pid__ok { 0.0_f32 } else { (self.position_loop__pid__bad + 1.0_f32).min(3.0_f32) }) } else { self.position_loop__pid__bad });
        let n_position_loop__amps__held = v_position_loop__amps__now;
        let n_thermal_fsm__mode = (if v___fire_40 { v_thermal_fsm__state } else { self.thermal_fsm__mode });
        let n_thermal_fsm__state__held = v_thermal_fsm__state__now;
        let n_thermal_fsm__scale__held = v_thermal_fsm__scale__now;
        let n_current_loop__pid__integral = (if v_current_loop__pid__rst { 0.0_f32 } else { (if v_current_loop__pid__deeper { self.current_loop__pid__integral } else { v_current_loop__pid__cand }).max((-24.0_f32)).min(24.0_f32) });
        let n_current_loop__pid__prev_meas = (if v_current_loop__pid__rst { 0.0_f32 } else { v_current_loop__pid__meas });
        let n_current_loop__pid__has_prev = (!v_current_loop__pid__rst);
        let n_current_loop__pid__filt = (if v_current_loop__pid__rst { 0.0_f32 } else { v_current_loop__pid__filt_d });
        let n_current_loop__pid__filt_init = (!v_current_loop__pid__rst);
        let n_current_loop__pid__bad = (if v_current_loop__pid__ok { 0.0_f32 } else { (self.current_loop__pid__bad + 1.0_f32).min(3.0_f32) });
        let out = (v_actuator__volts, v_telemetry__thermal_state, v_telemetry__setpoint,);
        self.__tick_40 = n___tick_40;
        self.position_loop__last_target = n_position_loop__last_target;
        self.position_loop__pid__integral = n_position_loop__pid__integral;
        self.position_loop__pid__prev_meas = n_position_loop__pid__prev_meas;
        self.position_loop__pid__has_prev = n_position_loop__pid__has_prev;
        self.position_loop__pid__filt = n_position_loop__pid__filt;
        self.position_loop__pid__filt_init = n_position_loop__pid__filt_init;
        self.position_loop__pid__bad = n_position_loop__pid__bad;
        self.position_loop__amps__held = n_position_loop__amps__held;
        self.thermal_fsm__mode = n_thermal_fsm__mode;
        self.thermal_fsm__state__held = n_thermal_fsm__state__held;
        self.thermal_fsm__scale__held = n_thermal_fsm__scale__held;
        self.current_loop__pid__integral = n_current_loop__pid__integral;
        self.current_loop__pid__prev_meas = n_current_loop__pid__prev_meas;
        self.current_loop__pid__has_prev = n_current_loop__pid__has_prev;
        self.current_loop__pid__filt = n_current_loop__pid__filt;
        self.current_loop__pid__filt_init = n_current_loop__pid__filt_init;
        self.current_loop__pid__bad = n_current_loop__pid__bad;
        out
    }
}

/// `sensor__theta`: a good sample lies in this range; a bad one may be NaN or +-inf.
pub const SENSOR__THETA: [f32; 2] = [(-100.0_f32), 100.0_f32];

/// `sensor__current`: a good sample lies in this range; a bad one may be NaN or +-inf.
pub const SENSOR__CURRENT: [f32; 2] = [(-64.0_f32), 64.0_f32];

/// `sensor__temp`: a good sample lies in this range; a bad one may be NaN or +-inf.
pub const SENSOR__TEMP: [f32; 2] = [(-40.0_f32), 200.0_f32];
